import Head from "next/head";

import SimpleLogin from "@/components/forms/login/SimpleLogin";

export default function Home() {
  return (
    <>
      <Head>
        <title>Chakra Components</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SimpleLogin/>
      </main>
    </>
  );
}
